version: "3.7"

services:
  switchbot-home-assistant:
    restart: unless-stopped
    build: ".."
    privileged: true
    network_mode: "host"
    environment:
      MQTT_URL: "tcp://mosquitto:1883"
